import time

while True:  
    print("Hacing nasa")
    time.sleep(1)
    print("Hacking nasa 15%")
    time.sleep(1)
    print("Hacking nasa 38%")
    time.sleep(1)
    print("Hacking nasa 78%")
    time.sleep(1)
    print("Hacking nasa 69%")
    time.sleep(1)
    print("Hacking nasa 100%")
    time.sleep(5)
    print("Done hacking nasa")
    time.sleep(1)
    print("The nasa secret is..")
    time.sleep(1)
    print("loading")
    time.sleep(5)
    print("Hack failed goverment counter hacked")
    time.sleep(1)
    print("Retrying Hack please wait...")
    time.sleep(5)
